"""message

Revision ID: 9df8eeb3a0cd
Revises: 224372b5cd29
Create Date: 2021-01-21 10:10:01.543008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9df8eeb3a0cd'
down_revision = '224372b5cd29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
