"""message

Revision ID: a64f4ecba60e
Revises: 8fd3ece55845
Create Date: 2021-01-18 16:10:02.063560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a64f4ecba60e'
down_revision = '8fd3ece55845'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slot', sa.Column('available_tokens', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('slot', 'available_tokens')
    # ### end Alembic commands ###
